plugins:
  - jekyll-feed
title: (peek-char t *sexp-life*)
description: b2's blog
author: 
  twitter: biofermin2
url: https://biofermin2.github.io
theme: jekyll-theme-hacker
feed:
  path: ./docs/feed.atom
